## Calculadora de Cadenas de Markov

In [6]:
import numpy as np 

### Utilizaremos el siguiente ejemplo para poder probar el software

<center><img src="IMAGENRESULTANTE.jpg" alt="No hay imagen" /></center>



Paso 1.- Definimos el arreglo inicial y le damos forma.
En este caso es de $5x5$ entonces lo dejaremos de esta siguiente manera ->

In [7]:
a = np.array([0,0.5,0,0,0.5,0.5,0,0.5,0,0,0,0.5,0,0.5,0,0,0,0.5,0,0.5,0.5,0,0,0.5,0])
newarr = a.reshape(5, 5)

Paso 2.- Visualizamos que nos salio correctamente --->

In [8]:
print(newarr)

[[0.  0.5 0.  0.  0.5]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.  0.  0.5 0.  0.5]
 [0.5 0.  0.  0.5 0. ]]


Paso 3.- Se van a definir las condiciones iniciales en 1 , para cada uno de los eventos, por eso lo vemos como valores de pivoteo en zero,one,two.
y para reforzar los cambiamos a la forma 5,1 para que nos queden de manera vertical

In [9]:
def iteraciones(numero):

    #validamos que sea un numero mayor a uno, recuerden que solo acepta enteros dado que se ocupara la variable
    #numero pare realizar iteraciones ---->

    #creamos los valores iniciales
    if(numero>=1):
        zero = np.array([1,0,0,0,0]).reshape(5, 1)
        one = np.array([0,1,0,0,0]).reshape(5, 1)
        two = np.array([0,0,1,0,0]).reshape(5, 1)
        three = np.array([0,0,0,1,0]).reshape(5, 1)
        four = np.array([0,0,0,0,1]).reshape(5, 1)
    #sugerencia: pueden mejorar este codigo añadiendo listas para crear las variables iniciales de forma dinamica


    #iteramos el numero de veces que se quiera realizar iteraciones
    for x in range(numero):

        #realizamos producto punto de cada uno de los estados iniciales por la matriz de transciocion
        zeroo = np.dot(newarr, zero).reshape(1,5) 
        onee = np.dot(newarr,one).reshape(1,5)
        twoo = np.dot(newarr,two).reshape(1,5)
        threee = np.dot(newarr,three).reshape(1,5)
        fourr = np.dot(newarr,four).reshape(1,5)

        #crearemos la nueva matriz de transicion , apilando cada uno de los arreglos anteriores
        nuevoarreglo = np.append(zeroo,onee)
        nuevoarreglo = np.append(nuevoarreglo,twoo)
        nuevoarreglo = np.append(nuevoarreglo,threee)
        nuevoarreglo = np.append(nuevoarreglo,fourr)

        #seleccionamos nuevamente los valores para que continuen las iteraciones
        zero = (nuevoarreglo[:5])  
        one = (nuevoarreglo[5:10])  
        two = (nuevoarreglo[10:15])  
        three = (nuevoarreglo[15:20]) 
        four = (nuevoarreglo[20:25]) 

    #para terminar construimos nuevamente la matriz final
    arreglo = np.append(zero,one)
    arreglo = np.append(arreglo,two)
    arreglo = np.append(arreglo,three)
    arreglo = np.append(arreglo,four)

    #la mostramos en pantalla con su respectiva forma 5x5
    print(arreglo.reshape(5,5))


In [10]:
#Basta con escribir el nombre de la funcion para mandarla a llamar
iteraciones(6)

[[0.3125   0.109375 0.234375 0.234375 0.109375]
 [0.109375 0.3125   0.109375 0.234375 0.234375]
 [0.234375 0.109375 0.3125   0.109375 0.234375]
 [0.234375 0.234375 0.109375 0.3125   0.109375]
 [0.109375 0.234375 0.234375 0.109375 0.3125  ]]
